TradingEnv:
  n_timesteps: !!float 1000000
  policy: "MlpPolicy"
  learning_rate: !!float 1.65e-05
  buffer_size: 100000
  learning_starts: 2000
  batch_size: 64
  tau: 1.0
  gamma: 0.999
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 1
  exploration_fraction: 0.3
  exploration_final_eps: 0.03

  policy_kwargs: "dict(net_arch=[256, 128])"